version: '3'
services:
  # You can also use a MongoDB Atlas, you just need to comment this Container out and change the config.json
  mongo:
    image: "mongo:latest"
    restart: unless-stopped
    hostname: mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
    ports:
      - "127.0.0.1:27017:27017"
    volumes:
      - "./mongodb/:/data/db"
  mcbulkaccountcheckerandwatcher:
    image: "cuddlycheetah/mcbulkaccountcheckerandwatcher"
    restart: unless-stopped
    # if you dont need the mongodb container, mae sure to remove these two lines too
    links:
      - mongo
    environment:
      - MONGO_DBURI=mongodb://admin:admin@mongo:27017
      - MONGO_DBNAME=mcaccountschecker
    ports:
      - "6969:6969/tcp"
